#' Read aerial survey DAS data
#'
#' Read fixed-width aerial survey DAS text file generated by turtle4d
#'   (or assocaited programs)
#'
#' @param file filename of an aerial survey DAS file
#'
#' @importFrom purrr set_names
#' @importFrom readr cols
#' @importFrom readr col_character
#' @importFrom readr read_fwf
#' @importFrom readr fwf_positions
#' @importFrom utils tail
#'
#' @details Parses DAS data into columns.
#'   Data must follow the following column number and format specifications:
#'   \tabular{lrr}{
#'     \emph{Item} \tab \emph{Columns} \tab \emph{Format}\cr
#'     Event number \tab 1-3\cr
#'     Event \tab 4\cr
#'     Effort dot \tab 5\cr
#'     Time \tab 6-11 \tab HHMMSS\cr
#'     Date \tab 13-18 \tab MMDDYY\cr
#'     Latitude \tab 20-28 \tab NDD:MM.MM\cr
#'     Longitude \tab 30-39 \tab WDDD:MM.MM\cr
#'     Data1 \tab 41-44 \cr
#'     Data2 \tab 45-49 \cr
#'     Data3 \tab 50-54\cr
#'     Data4 \tab 55-59\cr
#'     Data5 \tab 60-64\cr
#'     Data6 \tab 65-69\cr
#'     Data7 \tab 70+\cr
#'   }
#'   
#' @return Data frame with DAS data parsed into columns.
#'   The following columns were processed or added:
#'   \itemize{
#'     \item \code{DateTime}: of class \code{POSIXct}; combination of \code{Date} and \code{Time} columns 
#'     \item \code{Lat}: of class \code{numeric}; decimal degrees in range [-90, 90]
#'     \item \code{Lon}: of class \code{numeric}; decimal degrees in range [-180, 180]
#'     \item \code{Data#}: leading/trailing whitespace trimmed from columns in rows where \code{Event} is not "C" (i.e. a comment event)
#'     \item \code{file_das}: filename (note not full filepath) 
#'     \item \code{line_num}: line number of each data row
#'   }
#'
#' @examples
#' # TODO
#' # d <- do.call(rbind, lapply(list.files("../airdas/airDAS_files", full.names = TRUE), airdas_read))
#'
#' @export
airdas_read <- function(file) {
  stopifnot(inherits(file, "character"))
  
  fwf.start <- c(1,4,5, 06,13, 20,21,24, 30,31,35, 41,45,50,55,60,65,70)
  fwf.end   <- c(3,4,5, 11,18, 20,22,28, 30,33,39, 44,49,54,59,64,69,NA)
  
  # suppressWarnings() is for lines that do not have data in all columns
  x <- suppressWarnings(read_fwf(
    file, col_positions = fwf_positions(start = fwf.start, end = fwf.end),
    skip_empty_rows = FALSE,
    na = c("", " ", "  ", "   ", "    ", "     "),
    col_types = cols(.default = col_character()),
    trim_ws = FALSE
  )) %>%
    set_names(c("event_num", "Event", "EffortDot", "Time", "Date",
                "Lat1", "Lat2", "Lat3", "Lon1", "Lon2", "Lon3", 
                "Data1", "Data2", "Data3", "Data4", "Data5", "Data6", "Data7"))
  
  # Process data, and add file and line number columns
  x$EffortDot <- ifelse(is.na(x$EffortDot), FALSE, TRUE)
  x$Lat <- ifelse(x$Lat1 == "N", 1, -1) * (as.numeric(x$Lat2) + as.numeric(x$Lat3)/60)
  x$Lon <- ifelse(x$Lon1 == "E", 1, -1) * (as.numeric(x$Lon2) + as.numeric(x$Lon3)/60)
  x$DateTime <- strptime(paste(x$Date, x$Time), "%m%d%y %H%M%S")
  x$Data1 <- ifelse(x$Event == "C", x$Data1, trimws(x$Data1)) 
  x$Data2 <- ifelse(x$Event == "C", x$Data2, trimws(x$Data2)) 
  x$Data3 <- ifelse(x$Event == "C", x$Data3, trimws(x$Data3)) 
  x$Data4 <- ifelse(x$Event == "C", x$Data4, trimws(x$Data4)) 
  x$Data5 <- ifelse(x$Event == "C", x$Data5, trimws(x$Data5)) 
  x$Data6 <- ifelse(x$Event == "C", x$Data6, trimws(x$Data6)) 
  x$Data7 <- ifelse(x$Event == "C", x$Data7, trimws(x$Data7))
  x$file_das  <- tail(strsplit(file, "/")[[1]], 1)
  x$event_num <- as.numeric(x$event_num)
  x$line_num  <- seq_along(x$Event)
  
  # Data frame to return
  data.frame(
    Event = x$Event, EffortDot = x$EffortDot, DateTime = x$DateTime, 
    Lat = x$Lat, Lon = x$Lon,
    Data1 = x$Data1, Data2 = x$Data2, Data3 = x$Data3, Data4 = x$Data4, 
    Data5 = x$Data5, Data6 = x$Data6, Data7 = x$Data7,
    file_das = x$file_das, event_num = x$event_num, line_num = x$line_num, 
    stringsAsFactors = FALSE
  )
}
