#' Read AirDAS file(s)
#'
#' Read one or more fixed-width aerial survey DAS text file(s) 
#'   generated by TURTLEP (or an associated program) into a data frame, 
#'   where each line is data for a specific event
#'
#' @param file filename(s) of one or more AirDAS files
#' @param tz character; see \link[base]{strptime}. Default is UTC
#'
#' @importFrom readr cols
#' @importFrom readr col_character
#' @importFrom readr read_fwf
#' @importFrom readr fwf_positions
#'
#' @details Reads/parses aerial survey DAS data into columns of a data frame.
#'   If \code{file} contains multiple filenames, then the individual 
#'   data frames will be concatenated.
#'   The provided AirDAS file must adhere to the following column number and format specifications: 
#'   (see the "AirDAS_format" vignette for more information):
#'   \tabular{lrr}{
#'     \emph{Item}  \tab \emph{Columns} \tab \emph{Format}\cr
#'     Event number \tab 1-3\cr
#'     Event        \tab 4\cr
#'     Effort dot   \tab 5\cr
#'     Time         \tab 6-11  \tab HHMMSS\cr
#'     Date         \tab 13-18 \tab MMDDYY\cr
#'     Latitude     \tab 20-28 \tab NDD:MM.MM\cr
#'     Longitude    \tab 30-39 \tab WDDD:MM.MM\cr
#'     Data1        \tab 40-44\cr
#'     Data2        \tab 45-49\cr
#'     Data3        \tab 50-54\cr
#'     Data4        \tab 55-59\cr
#'     Data5        \tab 60-64\cr
#'     Data6        \tab 65-69\cr
#'     Data7        \tab 70+\cr
#'   }
#'    
#'   See \code{\link{airdas_format_pdf}} for more information about AirDAS format requirements
#'   
#' @return Data frame with AirDAS data read into columns.
#'   The data are read into the data frame as characters as described in 'Details',
#'   with the following exceptions:
#'   \tabular{lll}{
#'     \emph{Name} \tab \emph{Class} \tab \emph{Details}\cr
#'     EffortDot \tab logical   \tab \code{TRUE} if "." was present, and \code{FALSE} otherwise\cr
#'     DateTime  \tab POSIXct   \tab combination of 'Date' and 'Time' columns with time zone \code{tz}\cr
#'     Lat       \tab numeric   \tab 'Latitude' column converted to decimal degrees in range [-90, 90]\cr
#'     Lon       \tab numeric   \tab 'Longitude' column converted to decimal degrees in range [-180, 180]\cr
#'     Data#     \tab character \tab leading/trailing whitespace trimmed for non-comment events (i.e. rows where 'Event' is not "C" or "c")\cr
#'     file_das  \tab character \tab filename, extracted from the \code{file} argument using \code{\link[base]{basename}}\cr
#'     event_num \tab integer   \tab 'Event number' coerced to an integer using \code{\link[base:integer]{as.integer}}\cr
#'     line_num  \tab integer   \tab line number of each data row\cr
#'   }
#'
#' @examples
#' airdas_read(system.file("airdas_sample.das", package = "swfscAirDAS"))
#'
#' @export
airdas_read <- function(file, tz = "UTC") {
  stopifnot(inherits(file, "character"))
  
  if (length(file) < 1)
    stop("file must be a vector of one or more filename(s)")
  
  if (!all(file.exists(file)))
    stop("The supplied character string does not all name an existing file(s), ",
         "meaning file.exists(file) is FALSE")
  
  do.call(rbind, lapply(file, .airdas_read, tz = tz))
}


.airdas_read <- function(file, tz = "UTC") {
  # Input checks
  stopifnot(inherits(file, "character"))
  
  if (!file.exists(file)) 
    stop("The supplied character string does not name an existing file, ", 
         "meaning file.exists(file) is FALSE")
  
  # Start and end (inclusive) column indices
  fwf.start <- c(1,4,5, 06,13, 20,21,24, 30,31,35, 40,45,50,55,60,65,70)
  fwf.end   <- c(3,4,5, 11,18, 20,22,28, 30,33,39, 44,49,54,59,64,69,NA)
  
  # suppressWarnings() is for lines that do not have data in all columns
  x <- suppressWarnings(read_fwf(
    file, col_positions = fwf_positions(start = fwf.start, end = fwf.end),
    skip_empty_rows = FALSE,
    na = c("", " ", "  ", "   ", "    ", "     ", "      "),
    col_types = cols(.default = col_character()),
    trim_ws = FALSE
  )) 
  
  names(x) <- c("event_num", "Event", "EffortDot", "Time", "Date",
                "Lat1", "Lat2", "Lat3", "Lon1", "Lon2", "Lon3", 
                "Data1", "Data2", "Data3", "Data4", "Data5", "Data6", "Data7")
  
  # Process data, and add file and line number columns
  x$EffortDot <- ifelse(is.na(x$EffortDot), FALSE, TRUE)
  Lat <- ifelse(x$Lat1 == "N", 1, -1) * (as.numeric(x$Lat2) + as.numeric(x$Lat3)/60)
  Lon <- ifelse(x$Lon1 == "E", 1, -1) * (as.numeric(x$Lon2) + as.numeric(x$Lon3)/60)
  DateTime <- strptime(paste(x$Date, x$Time), "%m%d%y %H%M%S", tz = tz)
  file_das  <- basename(file)
  event_num <- suppressWarnings(as.integer(x$event_num)) #blank for # events
  line_num  <- seq_along(x$Event)
  
  data.df <- data.frame(
    Data1 = ifelse(toupper(x$Event) == "C", x$Data1, trimws(x$Data1)), 
    Data2 = ifelse(toupper(x$Event) == "C", x$Data2, trimws(x$Data2)), 
    Data3 = ifelse(toupper(x$Event) == "C", x$Data3, trimws(x$Data3)), 
    Data4 = ifelse(toupper(x$Event) == "C", x$Data4, trimws(x$Data4)), 
    Data5 = ifelse(toupper(x$Event) == "C", x$Data5, trimws(x$Data5)), 
    Data6 = ifelse(toupper(x$Event) == "C", x$Data6, trimws(x$Data6)), 
    Data7 = ifelse(toupper(x$Event) == "C", 
                   ifelse(trimws(x$Data7) == "", NA, x$Data7), 
                   trimws(x$Data7)), 
    stringsAsFactors = FALSE
  )
  # Data7 extra ^ is for entries with >6 spaces (eg "       ")
  data.df[data.df == ""] <- NA
  
  # Data frame to return
  data.frame(
    Event = x$Event, EffortDot = x$EffortDot, DateTime, Lat, Lon, data.df, 
    file_das, event_num, line_num, 
    stringsAsFactors = FALSE
  )
}
