#' Read aerial survey DAS data
#'
#' Read fixed-width aerial survey DAS text file generated by turtle4d,
#'   or associated programs
#'
#' @param file filename of an aerial survey DAS file
#'
#' @importFrom dplyr %>%
#' @importFrom purrr set_names
#' @importFrom readr cols
#' @importFrom readr col_character
#' @importFrom readr read_fwf
#' @importFrom readr fwf_positions
#' @importFrom utils tail
#'
#' @details Parses aerial DAS data into columns; adapted
#'   from \code{\link[swfscMisc]{das.read}}.
#'   The provided file must follow the following column number and format specifications:
#'   \tabular{lrr}{
#'     \emph{Item} \tab \emph{Columns} \tab \emph{Format}\cr
#'     Event number \tab 1-3\cr
#'     Event \tab 4\cr
#'     Effort dot \tab 5\cr
#'     Time \tab 6-11 \tab HHMMSS\cr
#'     Date \tab 13-18 \tab MMDDYY\cr
#'     Latitude \tab 20-28 \tab NDD:MM.MM\cr
#'     Longitude \tab 30-39 \tab WDDD:MM.MM\cr
#'     Data1 \tab 40-44 \cr
#'     Data2 \tab 45-49 \cr
#'     Data3 \tab 50-54\cr
#'     Data4 \tab 55-59\cr
#'     Data5 \tab 60-64\cr
#'     Data6 \tab 65-69\cr
#'     Data7 \tab 70+\cr
#'   }
#'   
#' @return Data frame with aerial DAS data parsed into columns.
#'   The following columns were processed or added:
#'   \itemize{
#'     \item \code{EffortDot}: logical; \code{TRUE} if "." present, \code{FALSE otherwise}
#'     \item \code{DateTime}: \code{POSIXct}; combination of \code{Date} and \code{Time} columns 
#'     \item \code{Lat}: \code{numeric}; decimal degrees in range [-90, 90]
#'     \item \code{Lon}: \code{numeric}; decimal degrees in range [-180, 180]
#'     \item \code{Data#}: leading/trailing whitespace trimmed for non-comment events (rows where \code{Event} is not "C" or "c")
#'     \item \code{file_das}: character; filename (note not full filepath) 
#'     \item \code{line_num}: integer; line number of each data row
#'   }
#'
#' @examples
#' # d <- do.call(rbind, lapply(list.files("../airdas/airDAS_files", full.names = TRUE), airdas_read))
#' airdas_read(system.file("airdas_sample.das", package = "swfscAirDAS"))
#'
#' @export
airdas_read <- function(file) {
  # Input check
  stopifnot(inherits(file, "character"))
  
  if (!file.exists(file)) 
    stop("The supplied character string does not name an existing file, ", 
         "meaning file.exists(file) is FALSE")
  
  # Start and end (inclusive) columns 
  fwf.start <- c(1,4,5, 06,13, 20,21,24, 30,31,35, 40,45,50,55,60,65,70)
  fwf.end   <- c(3,4,5, 11,18, 20,22,28, 30,33,39, 44,49,54,59,64,69,NA)
  
  # suppressWarnings() is for lines that do not have data in all columns
  x <- suppressWarnings(read_fwf(
    file, col_positions = fwf_positions(start = fwf.start, end = fwf.end),
    skip_empty_rows = FALSE,
    na = c("", " ", "  ", "   ", "    ", "     ", "      "),
    col_types = cols(.default = col_character()),
    trim_ws = FALSE
  )) %>%
    set_names(c("event_num", "Event", "EffortDot", "Time", "Date",
                "Lat1", "Lat2", "Lat3", "Lon1", "Lon2", "Lon3", 
                "Data1", "Data2", "Data3", "Data4", "Data5", "Data6", "Data7"))
  
  # Process data, and add file and line number columns
  x$EffortDot <- ifelse(is.na(x$EffortDot), FALSE, TRUE)
  Lat <- ifelse(x$Lat1 == "N", 1, -1) * (as.numeric(x$Lat2) + as.numeric(x$Lat3)/60)
  Lon <- ifelse(x$Lon1 == "E", 1, -1) * (as.numeric(x$Lon2) + as.numeric(x$Lon3)/60)
  DateTime <- strptime(paste(x$Date, x$Time), "%m%d%y %H%M%S")
  file_das  <- tail(strsplit(file, "/")[[1]], 1)
  event_num <- suppressWarnings(as.integer(x$event_num)) #blank for # events
  line_num  <- seq_along(x$Event)
  
  y <- data.frame(
    Data1 = ifelse(toupper(x$Event) == "C", x$Data1, trimws(x$Data1)), 
    Data2 = ifelse(toupper(x$Event) == "C", x$Data2, trimws(x$Data2)), 
    Data3 = ifelse(toupper(x$Event) == "C", x$Data3, trimws(x$Data3)), 
    Data4 = ifelse(toupper(x$Event) == "C", x$Data4, trimws(x$Data4)), 
    Data5 = ifelse(toupper(x$Event) == "C", x$Data5, trimws(x$Data5)), 
    Data6 = ifelse(toupper(x$Event) == "C", x$Data6, trimws(x$Data6)), 
    Data7 = ifelse(toupper(x$Event) == "C", 
                   ifelse(trimws(x$Data7) == "", NA, x$Data7), 
                   trimws(x$Data7)), 
    stringsAsFactors = FALSE
  )
  # Data7 extra ^ is for entries with >6 spaces (eg "       ")
  y[y == ""] <- NA

  # Data frame to return
  data.frame(
    Event = x$Event, EffortDot = x$EffortDot, DateTime, Lat, Lon, y, 
    file_das, event_num, line_num, 
    stringsAsFactors = FALSE
  )
}
